//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Адрес as \'Адрес\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'"})]
    [View("КлиентL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Адрес as \'Адрес\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fАдрес;
        
        private string fmail;
        
        private string fЛогин;
        
        private string fПароль;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// mail.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.mail CustomAttributes)

        // *** End programmer edit section *** (Клиент.mail CustomAttributes)
        [StrLen(255)]
        private string mail
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.mail Get start)

                // *** End programmer edit section *** (Клиент.mail Get start)
                string result = this.fmail;
                // *** Start programmer edit section *** (Клиент.mail Get end)

                // *** End programmer edit section *** (Клиент.mail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.mail Set start)

                // *** End programmer edit section *** (Клиент.mail Set start)
                this.fmail = value;
                // *** Start programmer edit section *** (Клиент.mail Set end)

                // *** End programmer edit section *** (Клиент.mail Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Адрес CustomAttributes)

        // *** End programmer edit section *** (Клиент.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Адрес Get start)

                // *** End programmer edit section *** (Клиент.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Клиент.Адрес Get end)

                // *** End programmer edit section *** (Клиент.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Адрес Set start)

                // *** End programmer edit section *** (Клиент.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Клиент.Адрес Set end)

                // *** End programmer edit section *** (Клиент.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Имя CustomAttributes)

        // *** End programmer edit section *** (Клиент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Имя Get start)

                // *** End programmer edit section *** (Клиент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Клиент.Имя Get end)

                // *** End programmer edit section *** (Клиент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Имя Set start)

                // *** End programmer edit section *** (Клиент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Клиент.Имя Set end)

                // *** End programmer edit section *** (Клиент.Имя Set end)
            }
        }
        
        /// <summary>
        /// Логин.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Логин CustomAttributes)

        // *** End programmer edit section *** (Клиент.Логин CustomAttributes)
        [StrLen(255)]
        public virtual string Логин
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Логин Get start)

                // *** End programmer edit section *** (Клиент.Логин Get start)
                string result = this.fЛогин;
                // *** Start programmer edit section *** (Клиент.Логин Get end)

                // *** End programmer edit section *** (Клиент.Логин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Логин Set start)

                // *** End programmer edit section *** (Клиент.Логин Set start)
                this.fЛогин = value;
                // *** Start programmer edit section *** (Клиент.Логин Set end)

                // *** End programmer edit section *** (Клиент.Логин Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Клиент.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Отчество Get start)

                // *** End programmer edit section *** (Клиент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Клиент.Отчество Get end)

                // *** End programmer edit section *** (Клиент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Отчество Set start)

                // *** End programmer edit section *** (Клиент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Клиент.Отчество Set end)

                // *** End programmer edit section *** (Клиент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Пароль.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Пароль CustomAttributes)

        // *** End programmer edit section *** (Клиент.Пароль CustomAttributes)
        [StrLen(255)]
        public virtual string Пароль
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Пароль Get start)

                // *** End programmer edit section *** (Клиент.Пароль Get start)
                string result = this.fПароль;
                // *** Start programmer edit section *** (Клиент.Пароль Get end)

                // *** End programmer edit section *** (Клиент.Пароль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Пароль Set start)

                // *** End programmer edit section *** (Клиент.Пароль Set start)
                this.fПароль = value;
                // *** Start programmer edit section *** (Клиент.Пароль Set end)

                // *** End programmer edit section *** (Клиент.Пароль Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Клиент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Get start)

                // *** End programmer edit section *** (Клиент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Клиент.Фамилия Get end)

                // *** End programmer edit section *** (Клиент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Set start)

                // *** End programmer edit section *** (Клиент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Клиент.Фамилия Set end)

                // *** End programmer edit section *** (Клиент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Snezhana_8.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Snezhana_8.Клиент));
                }
            }
        }
    }
}
