//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Менеджер.
    /// </summary>
    // *** Start programmer edit section *** (Менеджер CustomAttributes)

    // *** End programmer edit section *** (Менеджер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МенеджерE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    [View("МенеджерL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "СерияПаспорта as \'Серия паспорта\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    public class Менеджер : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private int fСерияПаспорта;
        
        private int fНомерПаспорта;
        
        private string fАдрес;
        
        private int fТелефон;
        
        // *** Start programmer edit section *** (Менеджер CustomMembers)

        // *** End programmer edit section *** (Менеджер CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Адрес CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Адрес Get start)

                // *** End programmer edit section *** (Менеджер.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Менеджер.Адрес Get end)

                // *** End programmer edit section *** (Менеджер.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Адрес Set start)

                // *** End programmer edit section *** (Менеджер.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Менеджер.Адрес Set end)

                // *** End programmer edit section *** (Менеджер.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Имя CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Имя Get start)

                // *** End programmer edit section *** (Менеджер.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Менеджер.Имя Get end)

                // *** End programmer edit section *** (Менеджер.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Имя Set start)

                // *** End programmer edit section *** (Менеджер.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Менеджер.Имя Set end)

                // *** End programmer edit section *** (Менеджер.Имя Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (Менеджер.НомерПаспорта CustomAttributes)
        public virtual int НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.НомерПаспорта Get start)

                // *** End programmer edit section *** (Менеджер.НомерПаспорта Get start)
                int result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (Менеджер.НомерПаспорта Get end)

                // *** End programmer edit section *** (Менеджер.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.НомерПаспорта Set start)

                // *** End programmer edit section *** (Менеджер.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (Менеджер.НомерПаспорта Set end)

                // *** End programmer edit section *** (Менеджер.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Отчество CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Отчество Get start)

                // *** End programmer edit section *** (Менеджер.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Менеджер.Отчество Get end)

                // *** End programmer edit section *** (Менеджер.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Отчество Set start)

                // *** End programmer edit section *** (Менеджер.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Менеджер.Отчество Set end)

                // *** End programmer edit section *** (Менеджер.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (Менеджер.СерияПаспорта CustomAttributes)
        public virtual int СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.СерияПаспорта Get start)

                // *** End programmer edit section *** (Менеджер.СерияПаспорта Get start)
                int result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (Менеджер.СерияПаспорта Get end)

                // *** End programmer edit section *** (Менеджер.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.СерияПаспорта Set start)

                // *** End programmer edit section *** (Менеджер.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (Менеджер.СерияПаспорта Set end)

                // *** End programmer edit section *** (Менеджер.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Телефон CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Телефон Get start)

                // *** End programmer edit section *** (Менеджер.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Менеджер.Телефон Get end)

                // *** End programmer edit section *** (Менеджер.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Телефон Set start)

                // *** End programmer edit section *** (Менеджер.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Менеджер.Телефон Set end)

                // *** End programmer edit section *** (Менеджер.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Фамилия Get start)

                // *** End programmer edit section *** (Менеджер.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Менеджер.Фамилия Get end)

                // *** End programmer edit section *** (Менеджер.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Фамилия Set start)

                // *** End programmer edit section *** (Менеджер.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Менеджер.Фамилия Set end)

                // *** End programmer edit section *** (Менеджер.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МенеджерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерE", typeof(IIS.Snezhana_8.Менеджер));
                }
            }
            
            /// <summary>
            /// "МенеджерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерL", typeof(IIS.Snezhana_8.Менеджер));
                }
            }
        }
    }
}
