//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Производитель.
    /// </summary>
    // *** Start programmer edit section *** (Производитель CustomAttributes)

    // *** End programmer edit section *** (Производитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроизводительE", new string[] {
            "Производитель as \'Производитель\'",
            "Страна as \'Страна\'"})]
    [View("ПроизводительL", new string[] {
            "Производитель as \'Производитель\'",
            "Страна as \'Страна\'"})]
    public class Производитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fПроизводитель;
        
        private string fСтрана;
        
        // *** Start programmer edit section *** (Производитель CustomMembers)

        // *** End programmer edit section *** (Производитель CustomMembers)

        
        /// <summary>
        /// Производитель.
        /// </summary>
        // *** Start programmer edit section *** (Производитель.Производитель CustomAttributes)

        // *** End programmer edit section *** (Производитель.Производитель CustomAttributes)
        [StrLen(255)]
        public virtual string Производитель
        {
            get
            {
                // *** Start programmer edit section *** (Производитель.Производитель Get start)

                // *** End programmer edit section *** (Производитель.Производитель Get start)
                string result = this.fПроизводитель;
                // *** Start programmer edit section *** (Производитель.Производитель Get end)

                // *** End programmer edit section *** (Производитель.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Производитель.Производитель Set start)

                // *** End programmer edit section *** (Производитель.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (Производитель.Производитель Set end)

                // *** End programmer edit section *** (Производитель.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Страна.
        /// </summary>
        // *** Start programmer edit section *** (Производитель.Страна CustomAttributes)

        // *** End programmer edit section *** (Производитель.Страна CustomAttributes)
        [StrLen(255)]
        public virtual string Страна
        {
            get
            {
                // *** Start programmer edit section *** (Производитель.Страна Get start)

                // *** End programmer edit section *** (Производитель.Страна Get start)
                string result = this.fСтрана;
                // *** Start programmer edit section *** (Производитель.Страна Get end)

                // *** End programmer edit section *** (Производитель.Страна Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Производитель.Страна Set start)

                // *** End programmer edit section *** (Производитель.Страна Set start)
                this.fСтрана = value;
                // *** Start programmer edit section *** (Производитель.Страна Set end)

                // *** End programmer edit section *** (Производитель.Страна Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроизводительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроизводительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроизводительE", typeof(IIS.Snezhana_8.Производитель));
                }
            }
            
            /// <summary>
            /// "ПроизводительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроизводительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроизводительL", typeof(IIS.Snezhana_8.Производитель));
                }
            }
        }
    }
}
