//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Способ1.
    /// </summary>
    // *** Start programmer edit section *** (Способ1 CustomAttributes)

    // *** End programmer edit section *** (Способ1 CustomAttributes)
    public enum Способ1
    {
        
        // *** Start programmer edit section *** (Способ1.Самовывоз CustomAttributes)

        // *** End programmer edit section *** (Способ1.Самовывоз CustomAttributes)
        [Caption("Самовывоз")]
        Самовывоз,
        
        // *** Start programmer edit section *** (Способ1.Курьером CustomAttributes)

        // *** End programmer edit section *** (Способ1.Курьером CustomAttributes)
        [Caption("Курьером")]
        Курьером,
    }
}
