//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип доставки.
    /// </summary>
    // *** Start programmer edit section *** (ТипДоставки CustomAttributes)

    // *** End programmer edit section *** (ТипДоставки CustomAttributes)
    public enum ТипДоставки
    {
        
        // *** Start programmer edit section *** (ТипДоставки.1 CustomAttributes)

        // *** End programmer edit section *** (ТипДоставки.1 CustomAttributes)
        [Caption("Безналичный расчет")]
        1,
        
        // *** Start programmer edit section *** (ТипДоставки.2 CustomAttributes)

        // *** End programmer edit section *** (ТипДоставки.2 CustomAttributes)
        [Caption("СПБ")]
        2,
        
        // *** Start programmer edit section *** (ТипДоставки.4 CustomAttributes)

        // *** End programmer edit section *** (ТипДоставки.4 CustomAttributes)
        [Caption("Электронные деньги")]
        4,
    }
}
